site_name: Vaishnavi Gobade â€” Cyber Security Portfolio
theme:
  name: material
plugins:
  - search 
nav:
  - Home: index.md
  - About Me: about.md
  - Projects: projects.md
  - Connect With Me: link.md
  - Certifications: certs.md
